name: Linting
on: [push]
jobs:
  LintingWithBlackAndFlake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Flake8
        run: |
          pip install flake8
      - name: Run Flake8
        run: |
          flake8 model.py
